language: java
jdk:
  - openjdk8

branches:
  only:
    - master

before_install:
  - chmod +x gradlew

cache:
  directories:
    - '$HOME/ .m2/repository'
    - '$HOME/ .gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r wearweather *
  - mkdir -p deploy
  - mv wearweather.zip deploy/wearweather.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: wearweather-springboot-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: wearweather-springboot-build
    key: wearweather.zip
    bundle_type: zip
    application: WearWeather
    deployment_group: WearWeather-group
    region: ap-northeast-2
    wait-until-deployed: true


notifications:
  email:
    recipients:
      - ansduf05@gmail.com

